In [2]:
import numpy as np
one_dis_array = np.array([1,2.2,3.3,4.4])
print(one_dis_array)

[1.  2.2 3.3 4.4]


In [3]:
two_dis_array=([[1,2],[2,3],[3,4]])
print(two_dis_array)

[[1, 2], [2, 3], [3, 4]]


In [4]:
random_int_between_10_and_100 = np.random.randint(low=10, high=101, size=(6))
print(random_int_between_10_and_100)

[23 53 63 85 40 41]


In [5]:
seq_of_integers = np.arange(1,11)
print(seq_of_integers)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = 0
label = label + noise
print(label)

[-0.49177126 -0.60546903  1.559005   -0.5433818  -0.45087934  1.60170952
 -0.67361589 -1.24829667 -0.38445525 -0.99949085 -1.66734261  1.23889129
  1.16423142  0.08935374 -0.84948386]
[-0.49177126 -0.60546903  1.559005   -0.5433818  -0.45087934  1.60170952
 -0.67361589 -1.24829667 -0.38445525 -0.99949085 -1.66734261  1.23889129
  1.16423142  0.08935374 -0.84948386]


In [18]:
import pandas as pd
my_data = np.array([[0,3],[10,7],[20,9],[30,14],[40,15]])
print(my_data)
my_column_name = ["temperature","activity"]
print(my_column_name)
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_name)
print(my_dataframe)

[[ 0  3]
 [10  7]
 [20  9]
 [30 14]
 [40 15]]
['temperature', 'activity']
   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [20]:
my_dataframe["adjusted"] = my_dataframe["activity"] + 2
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [21]:
print("Rows #0, #1, #2: ")
print(my_dataframe.head(3), '\n')

Rows #0, #1, #2: 
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 



In [22]:
print("Rows #2: ")
print(my_dataframe.iloc[[2]], '\n')

Rows #2: 
   temperature  activity  adjusted
2           20         9        11 



In [23]:
print("Rows #0, #1, #2 and #3: ")
print(my_dataframe[1:4], '\n')

Rows #0, #1, #2 and #3: 
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 



In [24]:
print("Column 'temperature':")
print(my_dataframe['temperature'])

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32
